spring:
  jdbc:
    datasource:
      driver: com.mysql.jdbc.Driver
      url: jdbc:mysql:///springboot_01
      username: root
      password: root
      type: druid
  resources:
    static-locations: classpath:/webapp/